### ISSUE TITLE
script fails on the line or so

### ISSUE THREAD

**Issue by lhirlimann** [mvexel/openstreetmap-vintage-tile-server#1]
Docker fails with :
```
+ service apache2 restart
 * Restarting Apache httpd web server apache2
[Tue Jun 21 15:34:06.529282 2022] [tile:notice] [pid 78:tid 139869066947648] Loading tile config ajt at /tile/ for zooms 0 - 20 from tile directory /var/lib/mod_tile with extension .png and mime type image/png
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
   ...done.
+ setPostgresPassword
+ sudo -u postgres psql -c 'ALTER USER renderer PASSWORD '\''renderer'\'''
ERROR:  role "renderer" does not exist
```

Data is ready but the last line `    docker run -p ${PORT}:80 -v openstreetmap-data-${YEAR}:/var/lib/postgresql/12/main -v openstreetmap-tiles-${YEAR}:/var/lib/mod_tile -d overv/openstreetmap-tile-server run
`
running on Fedora 36. What else can I provide to fix this ?

**Comment by mvexel** [comment]
this is an issue with the [openstreetmap tile server docker image](https://github.com/Overv/openstreetmap-tile-server). Perhaps they can help?

**Comment by mvexel** [comment]
It turns out that the tile server docker image folks changed the mount points. I am adapting the script and will push an update soon.

**Comment by mvexel** [comment]
Let me know if https://github.com/mvexel/openstreetmap-vintage-tile-server/commit/4ccd0f01f2c6a574e8246d49b92d129e64fb68c1 fixed it for you.

**Comment by mvexel** [comment]
Assuming the mentioned diff fixed it for you, if it didn't feel free to re-open!
