### ISSUE TITLE
Left side is grey

### ISSUE THREAD

**Issue by westnordost** [mvexel/openstreetmap-vintage-tile-server#2]
It looks like the left side is completely grey. Is the tileserver down?

**Comment by mvexel** [comment]
Yes. You'll have to provide your own tile endpoint.

**Comment by mvexel** [comment]
I updated the script ( see #1 ) and [posted on my OSM diary](https://www.openstreetmap.org/user/mvexel/diary/399939) so it should now be more accessible to create the tile endpoint. Closing this issue but let me know if you need anything!
